import morgan, { StreamOptions } from 'morgan'
import logger from './winston'

const stream: StreamOptions = {
	// use winston logger and remove the autogenerated \n nextline character
	write: message => logger.http(message.slice(0, -2)),
}

const morganMiddleware = morgan(
	':method :url :status :res[content-length] - :response-time ms',
	{ stream }
)

export default morganMiddleware
