name: CI

on:
    push:
        branches:
            - '**'
            
env:
    JSON_WEBTOKEN_SECRET: ${{ secrets.JSON_WEBTOKEN_SECRET }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.13.1
            - run: npm ci
            - run: npm run ci:server
            - run: npm run ci:client
